name: xpBuild
on:
  push:
    tags: ["xpv*"]
  pull_request:
    branches: ["xpro"]
  workflow_dispatch:
jobs:
  linux:
    uses: externpro/externpro/.github/workflows/build-linux.yml@25.07.6
    with:
      cmake-workflow-preset: LinuxRelease
    secrets: inherit
  macos:
    uses: externpro/externpro/.github/workflows/build-macos.yml@25.07.6
    with:
      cmake-workflow-preset: DarwinRelease
    secrets: inherit
  windows:
    uses: externpro/externpro/.github/workflows/build-windows.yml@25.07.6
    with:
      cmake-workflow-preset: WindowsRelease
    secrets: inherit
